
"use client";

import type { DiagnosticReport } from '@/lib/types';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { User, UserCog, HardHat, FileText, MoreVertical, Trash2 } from 'lucide-react';
import { format } from 'date-fns';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { cn } from '@/lib/utils';
import { Badge } from '../ui/badge';

interface DiagnosticReportCardProps {
  report: DiagnosticReport;
  onDelete: (id: string) => void;
  onProcess?: (id: string) => void;
}

const statusClassMap: Record<DiagnosticReport['status'], string> = {
  Processing: 'bg-yellow-500/20 text-yellow-700 border-yellow-500/30',
  Processed: 'bg-green-500/20 text-green-700 border-green-500/30',
  Error: 'bg-red-500/20 text-red-700 border-red-500/30',
};


export const DiagnosticReportCard = ({ report, onDelete, onProcess }: DiagnosticReportCardProps) => {

    const engine = (report.engines && report.engines.length > 0) ? report.engines[0] : null;
    const isProcessed = report.status === 'Processed';

    return (
        <Card className="flex flex-col h-full hover:shadow-lg transition-shadow duration-300">
            <CardHeader>
                 <div className="flex justify-between items-start">
                    <div className="flex-1">
                        <CardTitle className="flex items-center gap-2 font-headline text-lg">
                            <HardHat /> {report.customer?.name || 'Diagnostic Report'}
                        </CardTitle>
                        <CardDescription>
                           S/N: {engine?.serial || 'N/A'}
                        </CardDescription>
                    </div>
                    <AlertDialog>
                        <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                                <Button variant="ghost" size="icon">
                                    <MoreVertical className="h-4 w-4" />
                                </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                                <AlertDialogTrigger asChild>
                                    <DropdownMenuItem className="text-destructive" onSelect={(e) => e.preventDefault()}>
                                        <Trash2 className="mr-2 h-4 w-4" />
                                        Delete Report
                                    </DropdownMenuItem>
                                </AlertDialogTrigger>
                            </DropdownMenuContent>
                        </DropdownMenu>
                        <AlertDialogContent>
                            <AlertDialogHeader>
                                <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                                <AlertDialogDescription>
                                    This will permanently delete the report for {report.customer.name}.
                                </AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                                <AlertDialogCancel>Cancel</AlertDialogCancel>
                                <AlertDialogAction onClick={() => onDelete(report.id)}>
                                    Yes, delete report
                                </AlertDialogAction>
                            </AlertDialogFooter>
                        </AlertDialogContent>
                    </AlertDialog>
                </div>
            </CardHeader>
            <CardContent className="flex-1 space-y-3 text-sm">
                <div className="flex items-center gap-2 text-muted-foreground">
                    <FileText className="w-4 h-4" />
                    <span className="truncate">Files: {report.sourceFiles.length}</span>
                </div>
                 <div className="flex items-center gap-2 text-muted-foreground">
                    <UserCog className="w-4 h-4" />
                    <span>Generated by: {report.user.name}</span>
                </div>
            </CardContent>
            <CardFooter className="flex justify-between items-center">
                 <p className="text-xs text-muted-foreground">
                    {report.createdAt ? format(new Date(report.createdAt), 'dd/MM/yyyy p') : ''}
                </p>
                {isProcessed ? (
                    <Button asChild variant="outline">
                        <Link href={`/service-hub/yamaha-diagnostics/${report.id}`}>View Report</Link>
                    </Button>
                ) : (
                     <Badge className={cn(statusClassMap[report.status])}>{report.status}</Badge>
                )}
            </CardFooter>
        </Card>
    );
};
